-- Run this entire file in Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (char_length(username) between 3 and 30),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, username)
  values (new.id, coalesce(new.raw_user_meta_data->>'username', split_part(new.email,'@',1)));
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create table if not exists public.leaderboard_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  case_number text not null default '001',
  solve_seconds integer not null check (solve_seconds > 0),
  completed_at timestamptz not null default now(),
  unique(user_id, case_number)
);

create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  visited_at timestamptz not null default now(),
  visit_date date not null default current_date,
  page_path text not null
);

alter table public.profiles enable row level security;
alter table public.leaderboard_entries enable row level security;
alter table public.site_visits enable row level security;

create policy "Profiles are publicly readable" on public.profiles for select using (true);
create policy "Users update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Leaderboard is publicly readable" on public.leaderboard_entries for select using (true);
create policy "Users insert own scores" on public.leaderboard_entries for insert with check (auth.uid() = user_id);
create policy "Users update own scores" on public.leaderboard_entries for update using (auth.uid() = user_id);

create or replace function public.record_site_visit(visit_path text)
returns void language sql security definer set search_path = public as $$
  insert into public.site_visits(page_path) values (left(coalesce(visit_path,'/'), 250));
$$;
grant execute on function public.record_site_visit(text) to anon, authenticated;

create or replace view public.daily_stadium_attendance as
select visit_date, count(*) as total_visits
from public.site_visits
group by visit_date
order by visit_date desc;

revoke all on public.site_visits from anon, authenticated;
